name: code_demo
description: Just code demonstration with simple ui,but clean and modular architecture.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^8.0.0
  bloc_concurrency: ^0.2.5
  connectivity_plus: ^6.0.1
  dartz: ^0.10.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed_annotation: ^2.4.1
  auto_route_generator: ^8.0.0
  import_sorter: ^4.6.0
  logger: ^2.2.0
  mockito: ^5.4.4
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
